# encoding categorical data

In [1]:
# ordinal encoding[for features], label encoding[for labels] (converting categorical data into numeric data) 

In [10]:
import numpy as np
import pandas as pd

In [11]:
df = pd.read_csv('customer.csv')

In [12]:
df.sample(8)

age  gender   review education purchased
3    72  Female     Good        PG        No
45   61    Male     Poor        PG       Yes
1    68  Female     Poor        UG        No
10   98  Female     Good        UG       Yes
31   22  Female     Poor    School       Yes
0    30  Female  Average    School        No
37   94    Male  Average        PG       Yes
34   86    Male  Average    School        No

In [13]:
# age is numerical
# gender is nominal categrical data{it need one hot encoding} remove it for now
df = df.iloc[:, 2:]

In [14]:
df.sample(8)

review education purchased
35   Poor    School       Yes
16   Poor        UG       Yes
12   Poor    School        No
6    Good    School        No
38   Good    School        No
1    Poor        UG        No
15   Poor        UG        No
11   Good        UG       Yes

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:2],
                                                   df.iloc[:, 2],
                                                   test_size=0.3)

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
X_train

review education
9      Good        UG
36     Good        UG
29  Average        UG
17     Poor        UG
10     Good        UG
19     Poor        PG
27     Poor        PG
1      Poor        UG
8   Average        UG
3      Good        PG
5   Average    School
24  Average        PG
48     Good        UG
39     Poor        PG
37  Average        PG
22     Poor        PG
26     Poor        PG
32  Average        UG
40     Good    School
47     Good        PG
18     Good    School
4   Average        UG
46     Poor        PG
28     Poor    School
33     Good        PG
42     Good        PG
43     Poor        PG
12     Poor    School
44  Average        UG
6      Good    School
35     Poor    School
38     Good    School
13  Average    School
2      Good        PG
20  Average    School

In [21]:
X_test

review education
0   Average    School
25     Good    School
14     Poor        PG
41     Good        PG
34  Average    School
16     Poor        UG
21  Average        PG
45     Poor        PG
31     Poor    School
15     Poor        UG
49     Good        UG
7      Poor    School
30  Average        UG
23     Good    School
11     Good        UG

In [26]:
# specify the order to encoder passing lists
order = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
order.fit(X_train)



OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [27]:
X_train_encoded=order.transform(X_train)
X_test_encoded=order.transform(X_test)

In [28]:
X_train_encoded

array([[2., 1.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 2.],
       [1., 0.]])

In [29]:
X_test_encoded

array([[1., 0.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [2., 1.]])

In [30]:
order.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [31]:
#labelencoding for output label named purchased

In [33]:
from sklearn.preprocessing import LabelEncoder

In [35]:
label_enc= LabelEncoder()

In [36]:
label_enc.fit(y_train)

LabelEncoder()

In [37]:
label_enc.classes_

array(['No', 'Yes'], dtype=object)

In [40]:

y_train_encoded = label_enc.transform(y_train)
y_test_encoded = label_enc.transform(y_test)

In [41]:
y_train_encoded

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [42]:
y_test_encoded

array([0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1])