In [40]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [67]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend', 'Administration', 'Marketing Spend', 'Profit']]/10000)
np.random.seed(9)
df = df.head()
df

R&D Spend  Administration  Marketing Spend  Profit
0       17.0            14.0             47.0    19.0
1       16.0            15.0             44.0    19.0
2       15.0            10.0             41.0    19.0
3       14.0            12.0             38.0    18.0
4       14.0             9.0             37.0    17.0

In [68]:
df = df.iloc[:,0:-1]

In [69]:
df.head()

R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       16.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             37.0

In [70]:
#remove some values on purpose
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_10684\1608912696.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.NaN
C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_10684\1608912696.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.NaN
C:\Users\THINKPAD\AppData\Local\Temp\ipykernel_10684\1608912696.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.NaN


In [71]:
df.head()

R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0             NaN             38.0
4       14.0             9.0              NaN

In [72]:
#step 1 impute missing values with mean 
df0=pd.DataFrame()
df0['R&D Spend']=df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration']=df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend']=df['Marketing Spend'].fillna(df['Marketing Spend'].mean())


In [73]:
df0.head()

R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1       15.0            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             42.5

In [74]:

# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.NaN

df1.head()

R&D Spend  Administration  Marketing Spend
0       17.0            14.0             47.0
1        NaN            15.0             44.0
2       15.0            10.0             41.0
3       14.0            12.0             38.0
4       14.0             9.0             42.5

In [75]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

Administration  Marketing Spend
0            14.0             47.0
2            10.0             41.0
3            12.0             38.0
4             9.0             42.5

In [77]:
y = df1.iloc[[0,2,3,4],0]
y

0    17.0
2    15.0
3    14.0
4    14.0
Name: R&D Spend, dtype: float64

In [79]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\THINKPAD\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([16.5625])

In [80]:
df1.iloc[1,0] = 16.56
df1

R&D Spend  Administration  Marketing Spend
0      17.00            14.0             47.0
1      16.56            15.0             44.0
2      15.00            10.0             41.0
3      14.00            12.0             38.0
4      14.00             9.0             42.5

In [81]:
df1.iloc[3,1]=np.NaN
df1

R&D Spend  Administration  Marketing Spend
0      17.00            14.0             47.0
1      16.56            15.0             44.0
2      15.00            10.0             41.0
3      14.00             NaN             38.0
4      14.00             9.0             42.5

In [83]:
X=df1.iloc[[0,1,2,4],[0,2]]

In [84]:
X

R&D Spend  Marketing Spend
0      17.00             47.0
1      16.56             44.0
2      15.00             41.0
4      14.00             42.5

In [85]:
y=df1.iloc[[0,1,2,4],1]
y

0    14.0
1    15.0
2    10.0
4     9.0
Name: Administration, dtype: float64

In [86]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\THINKPAD\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.93717987])

In [87]:
df1.iloc[3,1]=8.93
df1

R&D Spend  Administration  Marketing Spend
0      17.00           14.00             47.0
1      16.56           15.00             44.0
2      15.00           10.00             41.0
3      14.00            8.93             38.0
4      14.00            9.00             42.5

In [97]:
df1.iloc[4,-1]=np.NaN
df1

R&D Spend  Administration  Marketing Spend
0      17.00           14.00             47.0
1      16.56           15.00             44.0
2      15.00           10.00             41.0
3      14.00            8.93             38.0
4      14.00            9.00              NaN

In [98]:
X= df1.iloc[0:4,0:2]
X

R&D Spend  Administration
0      17.00           14.00
1      16.56           15.00
2      15.00           10.00
3      14.00            8.93

In [99]:
y = df1.iloc[0:4,-1]

In [100]:
y

0    47.0
1    44.0
2    41.0
3    38.0
Name: Marketing Spend, dtype: float64

In [101]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\THINKPAD\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([37.73470093])

In [102]:

df1.iloc[4,-1] = 37.73
df1

R&D Spend  Administration  Marketing Spend
0      17.00           14.00            47.00
1      16.56           15.00            44.00
2      15.00           10.00            41.00
3      14.00            8.93            38.00
4      14.00            9.00            37.73

In [103]:
#ist iteration completed
df1-df0

R&D Spend  Administration  Marketing Spend
0       0.00            0.00             0.00
1       1.56            0.00             0.00
2       0.00            0.00             0.00
3       0.00           -3.07             0.00
4       0.00            0.00            -4.77

In [104]:
#iterate until the difference become zero