### self multiple linear regression class

In [8]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
X,y = load_diabetes(return_X_y=True)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=3)
X_train.shape 

(309, 10)

In [39]:
class LR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None
        
    def fit(self,X_train,y_train):
        X_train =np.insert(X_train,0,1,axis=1)
        betas=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_=betas[0]
        self.coef_=betas[1:]
        print(betas)
        
    def predict(self,X_test):
        y_pred=np.dot(X_test,self.coef_)+self.intercept_
        return y_pred

In [40]:
lr = LR()

In [41]:
lr.fit(X_train,y_train)

[ 1.53581958e+02 -3.52815107e-01 -2.87155875e+02  5.40993163e+02
  3.29302111e+02 -5.38843400e+02  2.12601930e+02  1.04014291e+01
  2.35046327e+02  5.98119178e+02  1.00428424e+02]


In [42]:
y_pred=lr.predict(X_test)

In [48]:
y_test

array([ 53.,  85.,  47.,  84., 174.,  42.,  44., 195., 150., 121., 143.,
       175., 219., 248.,  57.,  50.,  59., 166., 167., 134., 141., 118.,
       127., 171., 100., 144., 248., 198., 214., 220., 310.,  51., 129.,
       111., 151.,  85., 154.,  65.,  66., 131., 302., 275.,  97., 178.,
        55.,  71.,  53., 242., 182., 202., 214.,  88., 200., 178., 144.,
       230., 200., 303., 281., 197., 210.,  65.,  43., 219., 170.,  31.,
        99., 115.,  93., 177.,  52., 183., 156., 184.,  99.,  59., 217.,
        77., 102., 103., 275., 276., 122., 273., 132.,  70.,  71., 246.,
        77.,  89., 160., 109., 198.,  72., 274., 258., 121., 272., 168.,
       128.,  72., 280.,  84., 172., 192., 181., 140., 127.,  67., 232.,
       108., 125., 332., 118., 109., 257., 308.,  52., 164., 104.,  79.,
        65.,  52., 132., 225.,  92., 101.,  90., 235., 186.,  85., 245.,
        87.])

In [43]:
y_pred

array([ 96.50606657, 184.55943093, 101.09090389, 120.68287233,
       179.28755159,  81.46806637, 126.27672777, 235.61776315,
       150.24685614, 172.44059563, 174.45772855, 192.98866217,
       140.03713888, 225.60269547,  51.19606048, 146.33511266,
       122.46853758, 212.80549378, 189.39060187, 149.80297581,
       154.18724705, 103.68921523, 165.30800047, 172.85115888,
       152.48960579, 181.59420762, 201.34083634, 208.67309934,
       134.36267159, 162.95699915, 261.63107336, 121.43229312,
       190.47783003, 121.98219986, 166.51730335,  62.24587453,
       160.55791266, 102.7734328 , 121.57515741, 161.53417014,
       149.98123345, 214.59248519, 122.81475334, 124.56591654,
       155.76301015,  86.96821811, 115.7102145 , 258.39746511,
       149.12739001, 190.76326585, 146.66185102,  98.61631702,
       143.17783219, 188.99455083, 165.06378043, 141.91951462,
       114.57022837, 268.22272434, 256.71424152, 147.75611434,
       153.82531616, 125.36354886,  67.23449099, 144.14

In [44]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 44.04075505084234
MSE 3100.3934243323747
R2 score 0.4386218733716597


In [45]:
lr.coef_

array([-3.52815107e-01, -2.87155875e+02,  5.40993163e+02,  3.29302111e+02,
       -5.38843400e+02,  2.12601930e+02,  1.04014291e+01,  2.35046327e+02,
        5.98119178e+02,  1.00428424e+02])

In [46]:
lr.intercept_

153.58195762316092

In [47]:
# the accuracy results are same as scikit learn's accuracy , but r2 score is not that good