learning numpy

#creating numpy arrays

In [2]:
#1D tensor/vector
a = ([2,3,4])


In [3]:
print(a)

[2, 3, 4]


In [4]:
#2D tensor/matrix
b = ([[3,4],[5,6],[7,8]])

In [5]:
print(b)

[[3, 4], [5, 6], [7, 8]]


In [9]:
import numpy as np
a1 = np.random.random((4,3))
a1 = np.round(a1*150)
a1

array([[ 15., 147.,  69.],
       [ 37.,  92.,  74.],
       [102., 148.,  73.],
       [110.,  19.,  97.]])

In [10]:
np.max(a1)

148.0

In [12]:
np.min(a1)

15.0

In [13]:
a2 = np.random.random((4,3))
a2 = np.round(a2*100)
a2

array([[ 2., 68., 81.],
       [19., 54., 94.],
       [20., 56.,  5.],
       [94., 20., 24.]])

In [14]:
np.min(a1, axis = 1)

array([15., 37., 73., 19.])

In [15]:
np.min(a1, axis = 0)

array([15., 19., 69.])

In [16]:
np.max(a1, axis = 1)

array([147.,  92., 148., 110.])

In [17]:
np.min(a1, axis = 0)

array([15., 19., 69.])

In [19]:
np.prod(a1, axis = 1)

array([ 152145.,  251896., 1102008.,  202730.])

In [20]:
np.prod(a2, axis = 0)

array([  71440., 4112640.,  913680.])

In [21]:
np.mean(a2, axis = 0)

array([33.75, 49.5 , 51.  ])

In [22]:
np.median(a2, axis = 0)

array([19.5, 55. , 52.5])

In [23]:
np.std(a2, axis = 0)

array([35.51320177, 17.85357107, 37.3965239 ])

In [27]:
a3 = np.random.random((3,3))
a3 = np.round(a3*200)
a3
np.dot(a2,a3)

array([[22776., 20040.,  9115.],
       [22756., 23798.,  9715.],
       [11776.,  8076.,  2957.],
       [11392., 19564.,  3722.]])

In [28]:
a3

array([[ 50., 146.,  11.],
       [181.,  76.,  42.],
       [128., 180.,  77.]])

In [29]:
np.log(a3)


array([[3.91202301, 4.98360662, 2.39789527],
       [5.19849703, 4.33073334, 3.73766962],
       [4.85203026, 5.19295685, 4.34380542]])

In [30]:
np.exp(a3)

array([[5.18470553e+21, 2.55266814e+63, 5.98741417e+04],
       [4.04856601e+78, 1.01480039e+33, 1.73927494e+18],
       [3.88770841e+55, 1.48938420e+78, 2.75851345e+33]])

In [36]:
np.floor(np.random.random((2,2))*100)

array([[32., 21.],
       [94., 58.]])

In [37]:
np.ceil(np.random.random((2,2))*100)

array([[86., 10.],
       [99., 49.]])

In [38]:
np.round(np.random.random((2,2))*100)

array([[82., 96.],
       [99., 18.]])

In [41]:
a = np.arange(8)
b = np.arange(6).reshape(3,2)
c = np.arange(12).reshape(2,3,2)

In [43]:
a


array([0, 1, 2, 3, 4, 5, 6, 7])

In [44]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
a[6]

6

In [47]:
b[1,1]

3

In [48]:
c[1,2,0]

10

In [49]:
d = np.arange(16).reshape(2,2,2,2)

In [51]:
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [52]:
d[1,0,1,1]

11

In [54]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [55]:
a[:8 : 2]

array([0, 2, 4, 6])

In [56]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [57]:
b[1,:]

array([2, 3])

In [58]:
b[:,0]

array([0, 2, 4])

In [59]:
b[1,1]

3

In [61]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [62]:
b = np.arange(12).reshape(3,4)

In [63]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [67]:
b[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [69]:
b[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [70]:
b[::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [72]:
b[1, ::3]

array([4, 7])

In [75]:
b [:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
a = np.arange(27).reshape(3,3,3)

In [78]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [79]:
a[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [80]:
a[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
a[1,0:,1]

array([10, 13, 16])

In [82]:
a[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [83]:
a[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [88]:
for i in a:
    print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [89]:
for i in a:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [91]:
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [94]:
for i in np.nditer(b):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [95]:
np.transpose(b)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [96]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [105]:
#stacking - hstack, vstack
#same as concatenate in python
#It is not addition but still addition, i.e. put both tensors together.



In [101]:
a1 = np.arange(20).reshape(4,5)
a2 = np.arange(20).reshape(4,5)

In [102]:
a1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [104]:
np.hstack((a1,a2))

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 15, 16, 17, 18, 19]])

In [106]:
np.vstack((a1,a2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [107]:
np.vstack((a1,a2,a2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [111]:
np.vsplit(a1,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [112]:
np.hsplit(a1 ,5)

[array([[ 0],
        [ 5],
        [10],
        [15]]),
 array([[ 1],
        [ 6],
        [11],
        [16]]),
 array([[ 2],
        [ 7],
        [12],
        [17]]),
 array([[ 3],
        [ 8],
        [13],
        [18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]